package com.pojo;

import java.text.DecimalFormat;

// Generated Jan 15, 2013 9:10:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Fund generated by hbm2java
 */
public class Fund implements java.io.Serializable {

	private Integer id;
	private String name;
	private String symbol;
	private double lastDay;
	private String lastDayString;
	private double cur; 
	private String curString;
//	private Set fundPriceHistories = new HashSet(0);
	
	DecimalFormat df = new DecimalFormat("###,##0.00");

	public Fund() {
	}

	public Fund(String name, String symbol) {
		this.name = name;
		this.symbol = symbol;
//		this.positions = positions;
//		this.fundPriceHistories = fundPriceHistories;
	}
	
	public Double getLastDay() {
		return lastDay;
	}

	public void setLastDay(Double lastDay) {
		
		this.lastDay = lastDay;
		if(lastDay == 0){
			this.lastDayString = "-";
		}else {
			this.lastDayString = "$" + df.format(lastDay);
			
		}
		
	}

	public Double getCur() {
		return cur;
	}

	public void setCur(Double cur) {
		
		this.cur = cur;
		
		if(cur == 0){
			this.curString = "0.00";
		}else {
			this.curString = df.format(cur);
		}
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getLastDayString() {
		return lastDayString;
	}

	public void setLastDayString(String lastDayString) {
		this.lastDayString = lastDayString;
	}

	public String getCurString() {
		return curString;
	}

	public void setCurString(String curString) {
		this.curString = curString;
	}
}
