package com.pojo;

// Generated Jan 15, 2013 9:10:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FundPriceHistory generated by hbm2java
 */
public class FundPriceHistory implements java.io.Serializable {

	private Integer id;
	private Fund fund;
	private Date priceDate;
	private Long price;
//	private Set transactions = new HashSet(0);

	public FundPriceHistory() {
	}

	public FundPriceHistory(Fund fund) {
		this.fund = fund;
	}

	public FundPriceHistory(Fund fund, Date priceDate, Long price) {
		this.fund = fund;
		this.priceDate = priceDate;
		this.price = price;
//		this.transactions = transactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Fund getFund() {
		return this.fund;
	}

	public void setFund(Fund fund) {
		this.fund = fund;
	}

	public Date getPriceDate() {
		return this.priceDate;
	}

	public void setPriceDate(Date priceDate) {
		this.priceDate = priceDate;
	}

	public long getPrice() {
		if (this.price == null) {
			return 0;
		}
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

//	public Set getTransactions() {
//		return this.transactions;
//	}
//
//	public void setTransactions(Set transactions) {
//		this.transactions = transactions;
//	}

}
