package com.pojo;

// Generated Jan 15, 2013 9:10:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Fund generated by hbm2java
 */
public class Fund implements java.io.Serializable {

	private Integer id;
	private String name;
	private String symbol;
//	private Set fundPriceHistories = new HashSet(0);

	public Fund() {
	}

	public Fund(String name, String symbol) {
		this.name = name;
		this.symbol = symbol;
//		this.positions = positions;
//		this.fundPriceHistories = fundPriceHistories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
}
