package com.pojo;

// Generated Jan 15, 2013 9:10:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sysuser generated by hbm2java
 */
public class Sysuser implements java.io.Serializable {

	public static final int USER_TYPE_COSTOMER = 0;
	public static final int USER_TYPE_EMPLOYEE = 1;
	private Integer id;
	private String username;
	private String password;
	private String firstname;
	private String lastname;
	private String addrLine1;
	private String addrLine2;
	private String city;
	private String state;
	private String zip;
	private long cash;
	private double cashes;
	private int type;
//	private Set positions = new HashSet(0);
//	private Set transactions = new HashSet(0);

	public Sysuser() {
	}

	public Sysuser(String addrLine1, String addrLine2, String city,
			String state, String zip, long cash, int type) {
		this.addrLine1 = addrLine1;
		this.addrLine2 = addrLine2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.cash = cash;
		this.type = type;
		this.cashes = this.cash / 100.00;
	}

	public Sysuser(String username, String password, String firstname,
			String lastname, String addrLine1, String addrLine2, String city,
			String state, String zip, long cash, int type) {
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.addrLine1 = addrLine1;
		this.addrLine2 = addrLine2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.cash = cash;
		this.type = type;
		this.cashes = this.cash / 100.00;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getAddrLine1() {
		return this.addrLine1;
	}

	public void setAddrLine1(String addrLine1) {
		this.addrLine1 = addrLine1;
	}

	public String getAddrLine2() {
		return this.addrLine2;
	}

	public void setAddrLine2(String addrLine2) {
		this.addrLine2 = addrLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public long getCash() {
		return this.cash;
	}

	public void setCash(long cash) {
		this.cash = cash;
		this.cashes = this.cash / 100.00;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public double getCashes() {
		return cashes;
	}

	public void setCashes(double cashes) {
		this.cashes = cashes;
	}
}
