package com.pojo;

// Generated Jan 15, 2013 9:10:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private Integer id;
	private Sysuser sysuser;
	private FundPriceHistory fundPriceHistory;
	private Date executeDate;
	private Long shares;
	private Integer transactionType;
	private Integer status;

	public Transaction() {
	}

	public Transaction(Sysuser sysuser, FundPriceHistory fundPriceHistory,
			Date executeDate, Long shares, Integer transactionType, Integer status) {
		this.sysuser = sysuser;
		this.fundPriceHistory = fundPriceHistory;
		this.executeDate = executeDate;
		this.shares = shares;
		this.transactionType = transactionType;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Sysuser getSysuser() {
		return this.sysuser;
	}

	public void setSysuser(Sysuser sysuser) {
		this.sysuser = sysuser;
	}

	public FundPriceHistory getFundPriceHistory() {
		return this.fundPriceHistory;
	}

	public void setFundPriceHistory(FundPriceHistory fundPriceHistory) {
		this.fundPriceHistory = fundPriceHistory;
	}

	public Date getExecuteDate() {
		return this.executeDate;
	}

	public void setExecuteDate(Date executeDate) {
		this.executeDate = executeDate;
	}

	public Long getShares() {
		return this.shares;
	}

	public void setShares(Long shares) {
		this.shares = shares;
	}

	public Integer getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(Integer transactionType) {
		this.transactionType = transactionType;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
